# Generated by Django 6.0.5 on 2026-06-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='songs/raw/'),
        ),
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='track_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['album', 'track_number'], name='songs_song_album_i_1a8da4_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['status'], name='songs_song_status_2930ce_idx'),
        ),
    ]
