# Generated by Django 6.0.5 on 2026-06-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_song_audio_url_song_audio_song_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='song',
            name='songs_song_status_2930ce_idx',
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='status',
        ),
    ]
