# Generated by Django 6.0.5 on 2026-05-27 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_public_id_alter_artist_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
